{% set name = "coastsat-package" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/coastsat_package-{{ version }}.tar.gz
  sha256: 6ca89e8d2db119c71d3b5bde9307957cb584f2924ac99a46975659595a78dd93

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - google-auth
    - joblib
    - onnxruntime
    - pandas
    - pillow
    - pooch
    - pytz
    - requests
    - shapely
    - astropy
    - astropy-base
    - python >={{ python_min }}
    - scikit-learn
    - scikit-image >=0.25
    - earthengine-api >=0.1.304
    - jupyterlab >=3.0.0
    - geopandas
    - matplotlib-base
    - astropy-base
    - tqdm
    - importlib-resources
    - pyqt
    - scipy
    - numpy >=2
    - imageio

test:
  imports:
    - coastsat
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/SatelliteShorelines/coastsat_package
  summary: A Global shoreline mapping tool from satellite imagery
  license: GPL-2.0-or-later
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - 2320sharon
    - ocefpaf
