{% set name = "coastsat-package" %}
{% set version = "0.1.71" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/coastsat_package-{{ version }}.tar.gz
  sha256: edc1c2ebbd15baffeb95c7e8708db95819116d3e7e1c0d6cebf054113f350932

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - pip
  run:
    - scikit-learn
    - python >=3.8
    - scikit-image
    - earthengine-api >=0.1.304
    - jupyterlab >=3.0.0
    - geopandas
    - matplotlib-base
    - astropy
    - tqdm
    - importlib-resources
    - pyqt
    - scipy
    - numpy
    - imageio

test:
  imports:
    - coastsat
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/SatelliteShorelines/coastsat_package
  summary: A Global shoreline mapping tool from satellite imagery
  license: GPL-2.0-or-later
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - 2320sharon
    - ocefpaf
