{% set name = "coastsat-package" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/coastsat_package-{{ version }}.tar.gz
  sha256: 58bc69299b4c86e32c401644d484e8d1c726578d9b81e9f4269e12daaf1936c5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - astropy
    - python >={{ python_min }}
    - scikit-learn
    - scikit-image
    - earthengine-api >=0.1.304
    - jupyterlab >=3.0.0
    - geopandas
    - matplotlib-base
    - astropy-base
    - tqdm
    - importlib-resources
    - pyqt
    - scipy
    - numpy
    - imageio

test:
  imports:
    - coastsat
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/SatelliteShorelines/coastsat_package
  summary: A Global shoreline mapping tool from satellite imagery
  license: GPL-2.0-or-later
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - 2320sharon
    - ocefpaf
