{% set name = "coastsat-package" %}
{% set version = "0.1.36" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/coastsat_package-{{ version }}.tar.gz
  sha256: 91a6d95de050d073e0247ca8aa5cc9b93ca3a6e55e76b7188cdfea851cf2f54b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - pip
  run:
    - python >=3.8
    - scikit-image
    - earthengine-api >=0.1.304
    - matplotlib-base
    - astropy
    - tqdm
    - importlib-resources
    - pyqt
    - scipy
    - numpy

test:
  imports:
    - coastsat
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kvos/CoastSat
  summary: A Global shoreline mapping tool from satellite imagery
  license: GPL-3.0-or-later
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ocefpaf
