{% set name = "coastsat-package" %}
{% set version = "0.1.56" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/coastsat_package-{{ version }}.tar.gz
  sha256: 73a93bdd320a5c2ee310e48d3554a1b320e33edf68feb266ed34769411bc6eb2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - pip
  run:
    - imageio
    - python >=3.8
    - scikit-image
    - earthengine-api >=0.1.304
    - jupyterlab >=3.0.0
    - geopandas
    - matplotlib-base
    - astropy
    - tqdm
    - importlib-resources
    - pyqt
    - scipy
    - numpy

test:
  imports:
    - coastsat_package
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/2320sharon/coastsat_package
  summary: A Global shoreline mapping tool from satellite imagery
  license: GPL-3.0-or-later
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - 2320sharon
    - ocefpaf
